language: python
matrix:
  include:
    - python: 3.7
      dist: xenial

services:
  - docker

# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

before_script:
  - docker-compose -f ./local_dpos_testnet/docker-compose.yml up -d
  - sleep 10

# command to run tests
script:
  - make coverage

after_script:
  - make clean_local_testnets

after-success: 
  - codecov -e CODECOV_TOKEN

notifications:
  email: false
  slack:
    rooms: blocko:LwABz6vDzniWNDuDgtYIeqrf
    on_success: change
    on_failure: always 
