language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - make install
# command to run tests
script:
  - make coverage
after-success: 
  - codecov
notifications:
  email: false
  slack:
    rooms: blocko:LwABz6vDzniWNDuDgtYIeqrf
    on_success: change
    on_failure: always 
