language: python
matrix:
  include:
    - python: 3.7
      dist: xenial

services:
  - docker

# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

before_script:
  - docker-compose -f ./local_test_nodes/docker-compose.yml up -d
  - sleep 10

script:
  - pytest --cov-report=html --cov=aergo/ tests/
  - mypy -p aergo -p tests
  - flake8 --exclude=*_pb2_grpc.py,*_pb2.py,aergo_conf.py --ignore=E722,W503 --per-file-ignores="__init__.py:F401" aergo tests

after_script:
  - docker-compose -f ./local_test_nodes/docker-compose.yml down

after-success: 
  - codecov -e CODECOV_TOKEN

notifications:
  email: false
  slack:
    rooms: blocko:LwABz6vDzniWNDuDgtYIeqrf
    on_success: change
    on_failure: always 
