version: '3'
services:
  dpos1:
    image: aergo/node
    volumes:
      - ./dpos1:/aergo
      - ./genesis_dpos.json:/config/genesis.json
    ports:
      - "7845:7845"
    command: sh -c "aergosvr init --genesis /config/genesis.json --config /aergo/dpos1.toml && aergosvr --config /aergo/dpos1.toml"
    networks:
      docker_net:
        ipv4_address: "172.19.0.45"

  dpos2:
    image: aergo/node
    volumes:
      - ./dpos2:/aergo
      - ./genesis_dpos.json:/config/genesis.json
    ports:
      - "7846:7846"
    command: sh -c "aergosvr init --genesis /config/genesis.json --config /aergo/dpos2.toml && aergosvr --config /aergo/dpos2.toml"
    networks:
      docker_net:
        ipv4_address: "172.19.0.46"

  dpos3:
    image: aergo/node
    volumes:
      - ./dpos3:/aergo
      - ./genesis_dpos.json:/config/genesis.json
    command: sh -c "aergosvr init --genesis /config/genesis.json --config /aergo/dpos3.toml && aergosvr --config /aergo/dpos3.toml"
    networks:
      docker_net:
        ipv4_address: "172.19.0.47"

  raft:
    image: aergo/node
    volumes:
      - ./raft:/aergo
      - ./genesis_raft.json:/config/genesis.json
    ports:
      - "7848:7848"
    command: sh -c "aergosvr init --genesis /config/genesis.json --config /aergo/raft.toml && aergosvr --config /aergo/raft.toml"
    networks:
      docker_net:
        ipv4_address: "172.19.0.48"

networks:
  docker_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/21"