# ----------------------------------------------------------------------------
# Check keys from 'github.com/aergoio/aergo/config/types.go'
# Check default value of keys from 'github.com/aergoio/aergo/config/config.go'
# and fill the each default value
# ----------------------------------------------------------------------------

# aergo TOML Configuration File (https://github.com/toml-lang/toml)
# base configurations
datadir = "${AERGO_HOME}/data"
dbtype = "badgerdb"
enableprofile = false
profileport = 6060
enabletestmode = false
usetestnet = false
personal = true
authdir = "${AERGO_HOME}/auth"

[rpc]
netserviceaddr = "127.0.0.1"
netserviceport = 7845
netservicetrace = false
nstls = false
nscert = ""
nskey = ""
nscacert = ""
nsallowcors = false

[p2p]
# Set address and port to which the inbound peers connect, and don't set loopback address or private network unless used in local network
netprotocoladdr = ""
netprotocolport = 7846
npbindaddr = ""
npbindport = -1
# TLS and certificate is not applied in alpha release.
nptls = false
npcert = ""
# Set file path of key file
npkey = ""
npaddpeers = []
#nphiddenpeers = []
npdiscoverpeers = true
npmaxpeers = 100
nppeerpool = 100
npexposeself = true
npusepolaris = true
npaddpolarises = []
logfullpeerid = false

[auth]
enablelocalconf = false

[polaris]
allowprivate = false
genesisfile = ""

[blockchain]
# blockchain configurations
maxblocksize = 1048576 # 1 << 20
coinbaseaccount = ""
maxanchorcount = 20
# TODO: Check it's necessary for any reason
#verifiercount = 1 # Golang: int(math.Max(float64(runtime.NumCPU()/2), float64(1)))
forceresetheight = 0
zerofee = true
verifyonly = false
statetrace = 0

[mempool]
showmetrics = false
enablefadeout = false
fadeoutperiod = 12
# TODO: Check it's necessary for any reason
#verifiers = 0 # Golang: runtime.NumCPU()
dumpfilepath = "${AERGO_HOME}/mempool.dump"

[consensus]
enablebp = false
blockinterval = 1

[monitor]
protocol = ""
endpoint = ""

[account]
unlocktimeout = 60
