
datadir = "${AERGO_HOME}/data"
dbtype = "badgerdb"
enableprofile = false
profileport = 6060
enablerest = false
enabletestmode = false
personal = true

[rpc]
netserviceaddr = "127.0.0.1"
netserviceport = 7845
netservicetrace = false
#nstls = false
#nscert = ""
nskey = ""
#nsallowcors = false

[rest]
restport = 8080

[p2p]
netprotocoladdr = ""
netprotocolport = 7846
npbindaddr = ""
npbindport = -1
nptls = false
npcert = ""
npkey = ""
npaddpeers = []
npmaxpeers = 100
nppeerpool = 100

[blockchain]
maxblocksize = 1048576 # 1 << 20
coinbaseaccount = ""
maxanchorcount = 20
usefastsyncer = false

[mempool]
showmetrics = false
# TODO: check it's necessary for any reason
#verifiers = 0 # Golang: runtime.NumCPU()
dumpfilepath = "${AERGO_HOME}/mempool.dump"

[consensus]
enablebp = true
blockinterval = 1

[monitor]
protocol = ""
endpoint = ""

