# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x05types\"\x1a\n\x07\x41\x63\x63ount\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\"/\n\x0b\x41\x63\x63ountList\x12 \n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x0e.types.Accountb\x06proto3')



_ACCOUNT = DESCRIPTOR.message_types_by_name['Account']
_ACCOUNTLIST = DESCRIPTOR.message_types_by_name['AccountList']
Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:types.Account)
  })
_sym_db.RegisterMessage(Account)

AccountList = _reflection.GeneratedProtocolMessageType('AccountList', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTLIST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:types.AccountList)
  })
_sym_db.RegisterMessage(AccountList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNT._serialized_start=24
  _ACCOUNT._serialized_end=50
  _ACCOUNTLIST._serialized_start=52
  _ACCOUNTLIST._serialized_end=99
# @@protoc_insertion_point(module_scope)
