# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x05types\"\x94\x01\n\x0bPeerAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0e\n\x06peerID\x18\x03 \x01(\x0c\x12\x1d\n\x04role\x18\x04 \x01(\x0e\x32\x0f.types.PeerRole\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x11\n\taddresses\x18\x06 \x03(\t\x12\x13\n\x0bproducerIDs\x18\x07 \x03(\x0c\"\xa9\x01\n\x10\x41gentCertificate\x12\x13\n\x0b\x63\x65rtVersion\x18\x01 \x01(\r\x12\x0c\n\x04\x42PID\x18\x02 \x01(\x0c\x12\x10\n\x08\x42PPubKey\x18\x03 \x01(\x0c\x12\x12\n\ncreateTime\x18\x04 \x01(\x03\x12\x12\n\nexpireTime\x18\x05 \x01(\x03\x12\x0f\n\x07\x61gentID\x18\x06 \x01(\x0c\x12\x14\n\x0c\x41gentAddress\x18\x07 \x03(\x0c\x12\x11\n\tsignature\x18\x08 \x01(\x0c*C\n\x08PeerRole\x12\x11\n\rLegacyVersion\x10\x00\x12\x0c\n\x08Producer\x10\x01\x12\x0b\n\x07Watcher\x10\x02\x12\t\n\x05\x41gent\x10\x03\x62\x06proto3')

_PEERROLE = DESCRIPTOR.enum_types_by_name['PeerRole']
PeerRole = enum_type_wrapper.EnumTypeWrapper(_PEERROLE)
LegacyVersion = 0
Producer = 1
Watcher = 2
Agent = 3


_PEERADDRESS = DESCRIPTOR.message_types_by_name['PeerAddress']
_AGENTCERTIFICATE = DESCRIPTOR.message_types_by_name['AgentCertificate']
PeerAddress = _reflection.GeneratedProtocolMessageType('PeerAddress', (_message.Message,), {
  'DESCRIPTOR' : _PEERADDRESS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:types.PeerAddress)
  })
_sym_db.RegisterMessage(PeerAddress)

AgentCertificate = _reflection.GeneratedProtocolMessageType('AgentCertificate', (_message.Message,), {
  'DESCRIPTOR' : _AGENTCERTIFICATE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:types.AgentCertificate)
  })
_sym_db.RegisterMessage(AgentCertificate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEERROLE._serialized_start=344
  _PEERROLE._serialized_end=411
  _PEERADDRESS._serialized_start=22
  _PEERADDRESS._serialized_end=170
  _AGENTCERTIFICATE._serialized_start=173
  _AGENTCERTIFICATE._serialized_end=342
# @@protoc_insertion_point(module_scope)
