# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pmap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import node_pb2 as node__pb2
from . import p2p_pb2 as p2p__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npmap.proto\x12\x05types\x1a\nnode.proto\x1a\tp2p.proto\"X\n\x08MapQuery\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.types.Status\x12\r\n\x05\x61\x64\x64Me\x18\x02 \x01(\x08\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\x10\n\x08\x65xcludes\x18\x04 \x03(\x0c\"j\n\x0bMapResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.types.ResultStatus\x12%\n\taddresses\x18\x02 \x03(\x0b\x32\x12.types.PeerAddress\x12\x0f\n\x07message\x18\x03 \x01(\tb\x06proto3')



_MAPQUERY = DESCRIPTOR.message_types_by_name['MapQuery']
_MAPRESPONSE = DESCRIPTOR.message_types_by_name['MapResponse']
MapQuery = _reflection.GeneratedProtocolMessageType('MapQuery', (_message.Message,), {
  'DESCRIPTOR' : _MAPQUERY,
  '__module__' : 'pmap_pb2'
  # @@protoc_insertion_point(class_scope:types.MapQuery)
  })
_sym_db.RegisterMessage(MapQuery)

MapResponse = _reflection.GeneratedProtocolMessageType('MapResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSE,
  '__module__' : 'pmap_pb2'
  # @@protoc_insertion_point(class_scope:types.MapResponse)
  })
_sym_db.RegisterMessage(MapResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPQUERY._serialized_start=44
  _MAPQUERY._serialized_end=132
  _MAPRESPONSE._serialized_start=134
  _MAPRESPONSE._serialized_end=240
# @@protoc_insertion_point(module_scope)
