# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: polarrpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import node_pb2 as node__pb2
from . import rpc_pb2 as rpc__pb2
from . import metric_pb2 as metric__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epolarrpc.proto\x12\x05types\x1a\nnode.proto\x1a\trpc.proto\x1a\x0cmetric.proto\"(\n\x0bPaginations\x12\x0b\n\x03ref\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\r\"T\n\x0fPolarisPeerList\x12\r\n\x05total\x18\x01 \x01(\r\x12\x0f\n\x07hasNext\x18\x02 \x01(\x08\x12!\n\x05peers\x18\x03 \x03(\x0b\x32\x12.types.PolarisPeer\"h\n\x0bPolarisPeer\x12#\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x12.types.PeerAddress\x12\x11\n\tconnected\x18\x02 \x01(\x03\x12\x11\n\tlastCheck\x18\x03 \x01(\x03\x12\x0e\n\x06verion\x18\x04 \x01(\t\"1\n\rBLConfEntries\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x0f\n\x07\x65ntries\x18\x02 \x03(\t\"?\n\x0e\x41\x64\x64\x45ntryParams\x12\x0e\n\x06peerID\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04\x63idr\x18\x03 \x01(\t\"\x1e\n\rRmEntryParams\x12\r\n\x05index\x18\x01 \x01(\r2\xdd\x03\n\x11PolarisRPCService\x12\x31\n\tNodeState\x12\x0e.types.NodeReq\x1a\x12.types.SingleBytes\"\x00\x12\x31\n\x06Metric\x12\x15.types.MetricsRequest\x1a\x0e.types.Metrics\"\x00\x12;\n\x0b\x43urrentList\x12\x12.types.Paginations\x1a\x16.types.PolarisPeerList\"\x00\x12\x39\n\tWhiteList\x12\x12.types.Paginations\x1a\x16.types.PolarisPeerList\"\x00\x12\x39\n\tBlackList\x12\x12.types.Paginations\x1a\x16.types.PolarisPeerList\"\x00\x12\x35\n\rListBLEntries\x12\x0c.types.Empty\x1a\x14.types.BLConfEntries\"\x00\x12:\n\nAddBLEntry\x12\x15.types.AddEntryParams\x1a\x13.types.SingleString\"\x00\x12<\n\rRemoveBLEntry\x12\x14.types.RmEntryParams\x1a\x13.types.SingleString\"\x00\x62\x06proto3')



_PAGINATIONS = DESCRIPTOR.message_types_by_name['Paginations']
_POLARISPEERLIST = DESCRIPTOR.message_types_by_name['PolarisPeerList']
_POLARISPEER = DESCRIPTOR.message_types_by_name['PolarisPeer']
_BLCONFENTRIES = DESCRIPTOR.message_types_by_name['BLConfEntries']
_ADDENTRYPARAMS = DESCRIPTOR.message_types_by_name['AddEntryParams']
_RMENTRYPARAMS = DESCRIPTOR.message_types_by_name['RmEntryParams']
Paginations = _reflection.GeneratedProtocolMessageType('Paginations', (_message.Message,), {
  'DESCRIPTOR' : _PAGINATIONS,
  '__module__' : 'polarrpc_pb2'
  # @@protoc_insertion_point(class_scope:types.Paginations)
  })
_sym_db.RegisterMessage(Paginations)

PolarisPeerList = _reflection.GeneratedProtocolMessageType('PolarisPeerList', (_message.Message,), {
  'DESCRIPTOR' : _POLARISPEERLIST,
  '__module__' : 'polarrpc_pb2'
  # @@protoc_insertion_point(class_scope:types.PolarisPeerList)
  })
_sym_db.RegisterMessage(PolarisPeerList)

PolarisPeer = _reflection.GeneratedProtocolMessageType('PolarisPeer', (_message.Message,), {
  'DESCRIPTOR' : _POLARISPEER,
  '__module__' : 'polarrpc_pb2'
  # @@protoc_insertion_point(class_scope:types.PolarisPeer)
  })
_sym_db.RegisterMessage(PolarisPeer)

BLConfEntries = _reflection.GeneratedProtocolMessageType('BLConfEntries', (_message.Message,), {
  'DESCRIPTOR' : _BLCONFENTRIES,
  '__module__' : 'polarrpc_pb2'
  # @@protoc_insertion_point(class_scope:types.BLConfEntries)
  })
_sym_db.RegisterMessage(BLConfEntries)

AddEntryParams = _reflection.GeneratedProtocolMessageType('AddEntryParams', (_message.Message,), {
  'DESCRIPTOR' : _ADDENTRYPARAMS,
  '__module__' : 'polarrpc_pb2'
  # @@protoc_insertion_point(class_scope:types.AddEntryParams)
  })
_sym_db.RegisterMessage(AddEntryParams)

RmEntryParams = _reflection.GeneratedProtocolMessageType('RmEntryParams', (_message.Message,), {
  'DESCRIPTOR' : _RMENTRYPARAMS,
  '__module__' : 'polarrpc_pb2'
  # @@protoc_insertion_point(class_scope:types.RmEntryParams)
  })
_sym_db.RegisterMessage(RmEntryParams)

_POLARISRPCSERVICE = DESCRIPTOR.services_by_name['PolarisRPCService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAGINATIONS._serialized_start=62
  _PAGINATIONS._serialized_end=102
  _POLARISPEERLIST._serialized_start=104
  _POLARISPEERLIST._serialized_end=188
  _POLARISPEER._serialized_start=190
  _POLARISPEER._serialized_end=294
  _BLCONFENTRIES._serialized_start=296
  _BLCONFENTRIES._serialized_end=345
  _ADDENTRYPARAMS._serialized_start=347
  _ADDENTRYPARAMS._serialized_end=410
  _RMENTRYPARAMS._serialized_start=412
  _RMENTRYPARAMS._serialized_end=442
  _POLARISRPCSERVICE._serialized_start=445
  _POLARISRPCSERVICE._serialized_end=922
# @@protoc_insertion_point(module_scope)
