# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import p2p_pb2 as p2p__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x05types\x1a\tp2p.proto\"G\n\nMemberAttr\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0e\n\x06peerID\x18\x04 \x01(\x0c\"q\n\x10MembershipChange\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.types.MembershipChangeType\x12\x11\n\trequestID\x18\x02 \x01(\x04\x12\x1f\n\x04\x61ttr\x18\x03 \x01(\x0b\x32\x11.types.MemberAttr\"8\n\x15MembershipChangeReply\x12\x1f\n\x04\x61ttr\x18\x01 \x01(\x0b\x32\x11.types.MemberAttr\"-\n\rHardStateInfo\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\x04\".\n\x15GetClusterInfoRequest\x12\x15\n\rbestBlockHash\x18\x01 \x01(\x0c\"\xb2\x01\n\x16GetClusterInfoResponse\x12\x0f\n\x07\x63hainID\x18\x01 \x01(\x0c\x12\x11\n\tclusterID\x18\x02 \x01(\x04\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12#\n\x08mbrAttrs\x18\x04 \x03(\x0b\x32\x11.types.MemberAttr\x12\x13\n\x0b\x62\x65stBlockNo\x18\x05 \x01(\x04\x12+\n\rhardStateInfo\x18\x06 \x01(\x0b\x32\x14.types.HardStateInfo\"l\n\x12\x43onfChangeProgress\x12%\n\x05State\x18\x01 \x01(\x0e\x32\x16.types.ConfChangeState\x12\x0b\n\x03\x45rr\x18\x02 \x01(\t\x12\"\n\x07Members\x18\x03 \x03(\x0b\x32\x11.types.MemberAttr\"H\n\x10SnapshotResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.types.ResultStatus\x12\x0f\n\x07message\x18\x02 \x01(\t*9\n\x14MembershipChangeType\x12\x0e\n\nADD_MEMBER\x10\x00\x12\x11\n\rREMOVE_MEMBER\x10\x01*m\n\x0f\x43onfChangeState\x12\x1e\n\x1a\x43ONF_CHANGE_STATE_PROPOSED\x10\x00\x12\x1b\n\x17\x43ONF_CHANGE_STATE_SAVED\x10\x01\x12\x1d\n\x19\x43ONF_CHANGE_STATE_APPLIED\x10\x02\x62\x06proto3')

_MEMBERSHIPCHANGETYPE = DESCRIPTOR.enum_types_by_name['MembershipChangeType']
MembershipChangeType = enum_type_wrapper.EnumTypeWrapper(_MEMBERSHIPCHANGETYPE)
_CONFCHANGESTATE = DESCRIPTOR.enum_types_by_name['ConfChangeState']
ConfChangeState = enum_type_wrapper.EnumTypeWrapper(_CONFCHANGESTATE)
ADD_MEMBER = 0
REMOVE_MEMBER = 1
CONF_CHANGE_STATE_PROPOSED = 0
CONF_CHANGE_STATE_SAVED = 1
CONF_CHANGE_STATE_APPLIED = 2


_MEMBERATTR = DESCRIPTOR.message_types_by_name['MemberAttr']
_MEMBERSHIPCHANGE = DESCRIPTOR.message_types_by_name['MembershipChange']
_MEMBERSHIPCHANGEREPLY = DESCRIPTOR.message_types_by_name['MembershipChangeReply']
_HARDSTATEINFO = DESCRIPTOR.message_types_by_name['HardStateInfo']
_GETCLUSTERINFOREQUEST = DESCRIPTOR.message_types_by_name['GetClusterInfoRequest']
_GETCLUSTERINFORESPONSE = DESCRIPTOR.message_types_by_name['GetClusterInfoResponse']
_CONFCHANGEPROGRESS = DESCRIPTOR.message_types_by_name['ConfChangeProgress']
_SNAPSHOTRESPONSE = DESCRIPTOR.message_types_by_name['SnapshotResponse']
MemberAttr = _reflection.GeneratedProtocolMessageType('MemberAttr', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERATTR,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.MemberAttr)
  })
_sym_db.RegisterMessage(MemberAttr)

MembershipChange = _reflection.GeneratedProtocolMessageType('MembershipChange', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERSHIPCHANGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.MembershipChange)
  })
_sym_db.RegisterMessage(MembershipChange)

MembershipChangeReply = _reflection.GeneratedProtocolMessageType('MembershipChangeReply', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERSHIPCHANGEREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.MembershipChangeReply)
  })
_sym_db.RegisterMessage(MembershipChangeReply)

HardStateInfo = _reflection.GeneratedProtocolMessageType('HardStateInfo', (_message.Message,), {
  'DESCRIPTOR' : _HARDSTATEINFO,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.HardStateInfo)
  })
_sym_db.RegisterMessage(HardStateInfo)

GetClusterInfoRequest = _reflection.GeneratedProtocolMessageType('GetClusterInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCLUSTERINFOREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.GetClusterInfoRequest)
  })
_sym_db.RegisterMessage(GetClusterInfoRequest)

GetClusterInfoResponse = _reflection.GeneratedProtocolMessageType('GetClusterInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCLUSTERINFORESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.GetClusterInfoResponse)
  })
_sym_db.RegisterMessage(GetClusterInfoResponse)

ConfChangeProgress = _reflection.GeneratedProtocolMessageType('ConfChangeProgress', (_message.Message,), {
  'DESCRIPTOR' : _CONFCHANGEPROGRESS,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.ConfChangeProgress)
  })
_sym_db.RegisterMessage(ConfChangeProgress)

SnapshotResponse = _reflection.GeneratedProtocolMessageType('SnapshotResponse', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:types.SnapshotResponse)
  })
_sym_db.RegisterMessage(SnapshotResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEMBERSHIPCHANGETYPE._serialized_start=738
  _MEMBERSHIPCHANGETYPE._serialized_end=795
  _CONFCHANGESTATE._serialized_start=797
  _CONFCHANGESTATE._serialized_end=906
  _MEMBERATTR._serialized_start=32
  _MEMBERATTR._serialized_end=103
  _MEMBERSHIPCHANGE._serialized_start=105
  _MEMBERSHIPCHANGE._serialized_end=218
  _MEMBERSHIPCHANGEREPLY._serialized_start=220
  _MEMBERSHIPCHANGEREPLY._serialized_end=276
  _HARDSTATEINFO._serialized_start=278
  _HARDSTATEINFO._serialized_end=323
  _GETCLUSTERINFOREQUEST._serialized_start=325
  _GETCLUSTERINFOREQUEST._serialized_end=371
  _GETCLUSTERINFORESPONSE._serialized_start=374
  _GETCLUSTERINFORESPONSE._serialized_end=552
  _CONFCHANGEPROGRESS._serialized_start=554
  _CONFCHANGEPROGRESS._serialized_end=662
  _SNAPSHOTRESPONSE._serialized_start=664
  _SNAPSHOTRESPONSE._serialized_end=736
# @@protoc_insertion_point(module_scope)
